version: '3.9'
services:
  crypto-tracker-db:
    image: postgres
    restart: always
    container_name: crypto-tracker-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local-password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
